Add Text Align option
apognu/tuigreet pull request #136
Opened 2024-05-02 12:42 UTC by dthelegend

Hi

I added a text-align option to the prompt. I did this mainly so ASCII art I had in my `/etc/issue` showed up better, but I can see it being useful for other things as well.

I am not sure if you would rather include this in the new theme flag I saw recently added, but I wasn't sure how to properly extend the format to accommodate that so I added it as a new flag. Leaving the flag absent defaults to center align as before.

2024-05-02 14:04 UTC, apognu requested changes

2024-05-02 14:04 UTC, apognu commented on src/greeter.rs
> +      match value.to_uppercase().as_str() {
I think we can skip the case change here, and only match on the exact, lowercase, full-word alignement here. I don't think having both `l` and `lEfT` worth it.

The usage says `left`, `right` and `center`, let's follow this.

2024-05-02 14:04 UTC, apognu commented on src/ui/prompt.rs
I think something might have gone wrong with the formatter, here?

2024-05-02 14:04 UTC, apognu commented on src/greeter.rs
> +    opts.optopt("", "text-align", "alignment of text in the prompt container (default: 'center')", "[left|center|right]");
Could you also add this to the manpage, please?

And let's discuss about this being named `greet-align` (and therefore not applying to the message, only the greet / issue). Because while I agree rendering a nicely formatted issue is the way to go, I am a bit more skeptical about an error / prompt message.

2024-05-02 14:04 UTC, apognu commented
I added a few comments.

Also, thank you for not shoehorning this into the theme string. Even if that might be a good idea long-term, it needs some thinking on my part. 😁

2024-05-13 13:01 UTC, dthelegend commented on src/greeter.rs
> +    opts.optopt("", "text-align", "alignment of text in the prompt container (default: 'center')", "[left|center|right]");
Also added to the manpage

2024-05-13 13:48 UTC, apognu requested changes

2024-05-13 13:48 UTC, apognu commented on contrib/man/tuigreet-1.scd
> +    Alignment of the greeting text in the main prompt container
I am not on a computer right now, but this looks like spaces. SCD files need to use tabs. If this is a tab, you can ignore this comment.

You can try it by running `scdoc < contrib/man/tuigreet-1.scd`. In the future, it will be part of the test suite.

2024-05-13 13:58 UTC, dthelegend commented on contrib/man/tuigreet-1.scd
> +    Alignment of the greeting text in the main prompt container
It is, apologies, not worked with `*.scd` files before and defaulted to spaces. Fixed in [fbbc9c0](https://github.com/apognu/tuigreet/pull/136/commits/fbbc9c002f40006bc16818f72b4c3673b0fef893)

2024-05-13 16:09 UTC, merged

2024-05-13 16:09 UTC, apognu commented
Merged! Thanks you for the PR. :)