README: update instructions for Arch Linux
apognu/tuigreet pull request #93
Opened 2023-04-22 10:50 UTC by Narrat

As tuigreet got promoted into the repos :)

2023-06-12 06:36 UTC, hyperpuncher requested changes

2023-06-12 06:36 UTC, hyperpuncher commented on README.md
> +On ArchLinux, `tuigreet` is available from the [community](https://archlinux.org/packages/community/x86_64/greetd-tuigreet/) repo and is installable through pacman:
Community packages were combined to extra, that's the new link `[extra](https://archlinux.org/packages/extra/x86_64/greetd-tuigreet/)`

2023-06-12 18:15 UTC, Narrat commented on README.md
> +On ArchLinux, `tuigreet` is available from the [community](https://archlinux.org/packages/community/x86_64/greetd-tuigreet/) repo and is installable through pacman:
Right. Totally forgot about this.
Thanks for mentioning this.

2023-06-13 05:16 UTC, hyperpuncher approved these changes

2023-10-15 09:52 UTC, apognu commented
Manually rebased this and merged into `master`.

2023-10-15 09:52 UTC, closed without merging